### ISSUE TITLE
Error with -a option in MafAnnotator.py

### ISSUE THREAD

**Issue by StevenIg** [oncokb/oncokb-annotator#104]
Hello,

I try to annotate maf files with -a option but i have an error 

for example this command line with your exemples files 

python MafAnnotator.py -i $IMAF -o $OMAF -b TOKEN-c $IC -a

Traceback (most recent call last):
  File "/illumina/software/oncokb-annotator/MafAnnotator.py", line 117, in <module>
    args.func(args)
  File "/illumina/software/oncokb-annotator/MafAnnotator.py", line 94, in main
    cancertypemap, True, argv.annotate_hotspots, user_input_query_type, default_reference_genome)
  File "/illumina/software/oncokb-annotator/AnnotatorCore.py", line 359, in processalterationevents
    inithotspots()
  File "/illumina/software/oncokb-annotator/AnnotatorCore.py", line 235, in inithotspots
    curatedgenes |= set(missensesinglehotspots.keys())
TypeError: unsupported operand type(s) for |=: 'list' and 'set'

The same command line without -a works very well.

Thanks you,

Steven

**Comment by zhx828** [comment]
@StevenIg thanks for reporting the issue. If you use the latest version v2.5.0 the issue should be gone.
