### ISSUE TITLE
Fix python building issue in Windows

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb-annotator#108]
The python tests under Windows are currently failing with the following error: https://github.com/oncokb/oncokb-annotator/runs/1333514005?check_suite_focus=true

Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.3.0.tar.gz (54 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\hostedtoolcache\windows\python\3.7.9\x64\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\pip-install-70cmqhna\\kiwisolver\\setup.py'"'"'; __file__='"'"'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\pip-install-70cmqhna\\kiwisolver\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\RUNNER~1\AppData\Local\Temp\pip-pip-egg-info-rd9u6gf_'
         cwd: C:\Users\RUNNER~1\AppData\Local\Temp\pip-install-70cmqhna\kiwisolver\
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: 'c:\hostedtoolcache\windows\python\3.7.9\x64\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\pip-wheel-1t3zdktl\\cppy\\setup.py'"'"'; __file__='"'"'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\pip-wheel-1t3zdktl\\cppy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\RUNNER~1\AppData\Local\Temp\pip-wheel-tzdkvg4z'
           cwd: C:\Users\RUNNER~1\AppData\Local\Temp\pip-wheel-1t3zdktl\cppy\
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for cppy
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\hostedtoolcache\\windows\\python\\3.7.9\\x64\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpl_hbrcgx', '--quiet', 'cppy>=1.1.0']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-install-70cmqhna\kiwisolver\setup.py", line 81, in <module>
        cmdclass={'build_ext': BuildExt},
      File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\setuptools\__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\setuptools\__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\setuptools\dist.py", line 698, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\pkg_resources\__init__.py", line 783, in resolve
        replace_conflicting=replace_conflicting
      File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\pkg_resources\__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\pkg_resources\__init__.py", line 1078, in obtain
        return installer(requirement)
      File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\setuptools\dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['c:\\hostedtoolcache\\windows\\python\\3.7.9\\x64\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpl_hbrcgx', '--quiet', 'cppy>=1.1.0']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by zhx828** [comment]
This is related `https://github.com/matplotlib/matplotlib/issues/18846`
