### ISSUE TITLE
Error: Max retries exceeded with url

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb-annotator#141]
Some of the users experience the following errors. Seems related to the SSL, but have difficult time reproducing.

```
INFO:MafAnnotator:annotating /data_mutations_extended.txt ...
INFO:AnnotatorCore:1000
Traceback (most recent call last):
  File "MafAnnotator.py", line 116, in <module>
    args.func(args)
  File "MafAnnotator.py", line 93, in main
    cancertypemap, argv.annotate_hotspots, user_input_query_type, default_reference_genome)
  File "/Users/kundrar/github_repos/oncokb-annotator/AnnotatorCore.py", line 402, in processalterationevents
    cancerTypeMap, annotatehotspots, default_reference_genome)
  File "/Users/kundrar/github_repos/oncokb-annotator/AnnotatorCore.py", line 497, in process_alteration
    annotations = pull_protein_change_info(queries,annotatehotspots)
  File "/Users/kundrar/github_repos/oncokb-annotator/AnnotatorCore.py", line 1465, in pull_protein_change_info
    response = makeoncokbpostrequest(url, queries)
  File "/Users/kundrar/github_repos/oncokb-annotator/AnnotatorCore.py", line 208, in makeoncokbpostrequest
    timeout=REQUEST_TIMEOUT)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.oncokb.org', port=443): Max retries exceeded with url: /api/v1/annotate/mutations/byProteinChange (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))
```

**Comment by zhx828** [comment]
This issue shows up again for another user while annotating a big file. It was running ok but got the same error at the end.

**Comment by zhx828** [comment]
- https://togithub.com/psf/requests/issues/4246 indicates that the potential issue could be the local OpenSSL out of date.

**Comment by zhx828** [comment]
This exception can be throw due to varies reasons, we need to look into the details at the end of exception for specific cases.
