### ISSUE TITLE
Error running MafAnnotator.py

### ISSUE THREAD

**Issue by patidarr** [oncokb/oncokb-annotator#15]
Hi @jjgao,

I can figure out what I am doing wrong to get this error:
[patidarr@cn3151 processedDATA]$ python /data/MoCha/patidarr/oncokb-annotator/MafAnnotator.py -i LG0520/20170910/LG0520.consensus.maf -o LG0520/20170910/oncoKB/LG0520.maf -t LUSC
annotating LG0520/20170910/LG0520.consensus.maf...
Traceback (most recent call last):
  File "/data/MoCha/patidarr/oncokb-annotator/MafAnnotator.py", line 81, in <module>
    main(sys.argv[1:])
  File "/data/MoCha/patidarr/oncokb-annotator/MafAnnotator.py", line 68, in main
    processalterationevents(inputmaffile, outputmaffile, previousresultfile, defaultcancertype, cancertypemap, False)
  File "/gpfs/gsfs6/users/MoCha/patidarr/oncokb-annotator/AnnotatorCore.py", line 127, in processalterationevents
    inithotspots()
  File "/gpfs/gsfs6/users/MoCha/patidarr/oncokb-annotator/AnnotatorCore.py", line 118, in inithotspots
    missensesinglehotspots = gethotspots(cancerhotspotsbaseurl+"/api/hotspots/single", "single residue")
  File "/gpfs/gsfs6/users/MoCha/patidarr/oncokb-annotator/AnnotatorCore.py", line 95, in gethotspots
    hotspotsjson = json.load(urllib.urlopen(url))
  File "/usr/local/Anaconda/envs/py2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Anaconda/envs/py2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Anaconda/envs/py2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Anaconda/envs/py2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

I used vcf2maf to generate the MAF file and I have used the similar maf file on another patient and it has worked, there are some 70 patients its not working on. 

Any insight would be very helpful.

Thanks,
Rajash

**Comment by jjgao** [comment]
@patidarr Please pull the new code and try again. There was some change related to the cancerhotspots.org url that should fix the issue.

**Comment by patidarr** [comment]
Thank you @jjgao !!
