### ISSUE TITLE
Failed run on "CnaAnnotator.py"

### ISSUE THREAD

**Issue by gongyixiao** [oncokb/oncokb-annotator#19]
Hi, there, 

I recently cloned this version of oncokb_annotator and run "CnaAnnotator.py" using the following command and got the following error:

```
[gongy@luna BRAF_Fusions]$ which python
/opt/common/CentOS_6-dev/python/python-2.7.10/bin/python
[gongy@luna BRAF_Fusions]$ python ~/utilities/pipelines/oncokb-annotator/CnaAnnotator.py -i /home/jonssonp/res/dmp/mskimpact/data_CNA.txt -o test
annotating /home/jonssonp/res/dmp/mskimpact/mskimpact/data_CNA.txt...
Traceback (most recent call last):
  File "/home/gongy/utilities/pipelines/oncokb-annotator/CnaAnnotator.py", line 72, in <module>
    main(sys.argv[1:])
  File "/home/gongy/utilities/pipelines/oncokb-annotator/CnaAnnotator.py", line 59, in main
    processcnagisticdata(inputcnafile, outputcnafile, previousresultfile, defaultcancertype, cancertypemap, False)
  File "/home/gongy/utilities/pipelines/oncokb-annotator/AnnotatorCore.py", line 400, in processcnagisticdata
    outf.write(oncokbinfo)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 62: ordinal not in range(128)
[gongy@luna BRAF_Fusions]$ diff /home/bandlamc/ifs_work/git/oncokb-annotator/CnaAnnotator.py ~/utilities/pipelines/oncokb-annotator/CnaAnnotator.py
```

I tried to use an older version of "CnaAnnotator.py" from the following directory and it works well: 
```
/home/bandlamc/ifs_work/git/oncokb-annotator/CnaAnnotator.py
```

Please let me know if you can't access to any of these files. 

Thanks.
Yixiao Gong

**Comment by gongyixiao** [comment]
That was quick! Thank you! 👍

**Comment by jjgao** [comment]
Thanks for reporting this. Please pull the latest code. @gongyixiao
